# Header
menu:
  Home: /
  Archives: /archives
  About: /About
github_connect: https://github.com/SonicDMG
twitter_connect: https://twitter.com/SonicDMG
linkedin_connect: https://www.linkedin.com/in/david-gilardi
youtube_connect: https://www.youtube.com/channel/UCOYqZ4ckEso2-lYQjzpeaoQ

# Language
language: default

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
